In [2]:
import numpy as np

In [3]:
A = np.array([[0,-1],[1,0]])
A

array([[ 0, -1],
       [ 1,  0]])

In [4]:
AT = A.transpose()
A.dot(AT)

array([[1, 0],
       [0, 1]])

In [5]:
#верхнетреугольная
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
B

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#Нижнетреугольная
C = np.array([[1,0,0],[0,1,0],[0,0,1]])
C

In [10]:
BT = B.transpose()
B.dot(BT)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
C = np.array([[0,2,],[1,0,]])
C

array([[0, 2],
       [1, 0]])

In [8]:
D = np.array([[1,2],[2,5]])
D

array([[1, 2],
       [2, 5]])

In [9]:
r = np.array([[2,2],[1,3]])
r
#собственные значения = 1,4

# собственные векторы:

a = np.array([2,1])
b = np.array([1,1])