In [1]:
import numpy as np

In [27]:
A = np.array([[2,0,0],[0,2,0],[0,0,2]])
A

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

In [34]:
B = np.array([[1,0,3],[0,2,0],[0,0,0]])
B

array([[1, 0, 3],
       [0, 2, 0],
       [0, 0, 0]])

In [39]:
C = np.array([[0,0,0],[0,2,0],[1,0,3]])
C

array([[0, 0, 0],
       [0, 2, 0],
       [1, 0, 3]])

In [44]:
D = np.array([[1,2],[2,5]])
D

array([[1, 2],
       [2, 5]])

In [46]:
r = np.array([[2,2],[1,3]])
r
#собственные значения = 1,4

# собственные векторы:

a = np.array([2,1])
b = np.array([1,1])

array([[2, 2],
       [1, 3]])