In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
adult = pd.read_csv('adult.csv')

In [14]:
adult.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [23]:
adult['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [24]:
from sklearn.linear_model import LogisticRegression

In [129]:
selected_columns = adult[['age', 'gender', 'capital-gain', 'capital-loss', 'hours-per-week', 'education', 'income' ]]
# столбец education является категориальной переменной
# переведем ее в значения 0 и 1, добавив столбцы с соответствующими названиями
X = pd.get_dummies(selected_columns, columns = ['education', 'gender'])
# столбец income является целевой переменной, удаляем его из X
del X['income']
X.head()

age  capital-gain  capital-loss  hours-per-week  education_10th  \
0   25             0             0              40               0   
1   38             0             0              50               0   
2   28             0             0              40               0   
3   44          7688             0              40               0   
4   18             0             0              30               0   

   education_11th  education_12th  education_1st-4th  education_5th-6th  \
0               1               0                  0                  0   
1               0               0                  0                  0   
2               0               0                  0                  0   
3               0               0                  0                  0   
4               0               0                  0                  0   

   education_7th-8th  ...  education_Assoc-voc  education_Bachelors  \
0                  0  ...                    0                    0   
1                  0  ...                    0                    0   
2                  0  ...                    0                    0   
3                  0  ...                    0                    0   
4                  0  ...                    0                    0   

   education_Doctorate  education_HS-grad  education_Masters  \
0                    0                  0                  0   
1                    0                  1                  0   
2                    0                  0                  0   
3                    0                  0                  0   
4                    0                  0                  0   

   education_Preschool  education_Prof-school  education_Some-college  \
0                    0                      0                       0   
1                    0                      0                       0   
2                    0                      0                       0   
3                    0                      0                       1   
4                    0                      0                       1   

   gender_Female  gender_Male  
0              0            1  
1              0            1  
2              0            1  
3              0            1  
4              1            0  

[5 rows x 22 columns]

In [130]:
# целевая переменная (столбец income) снова является категориальной
# переведем значения столбца в числа, оставив один столбец
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


In [131]:
le.fit(adult['income'])

LabelEncoder()

In [132]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [133]:
le.transform( [ '<=50K', '>50K', '>50K' ] )

array([0, 1, 1], dtype=int64)

In [134]:
y = pd.Series(data = le.transform( adult[ 'income' ] ))
y.head

<bound method NDFrame.head of 0        0
1        0
2        1
3        1
4        0
        ..
48837    0
48838    1
48839    0
48840    0
48841    1
Length: 48842, dtype: int32>

In [169]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [170]:
model = make_pipeline(StandardScaler(), LogisticRegression())

In [171]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.3, random_state=42)

In [172]:
model.fit(X_train, y_train)
predictions = model1.predict_proba(X_test)

In [173]:
predictions[:5]

array([[0.90579355, 0.09420645],
       [0.91728531, 0.08271469],
       [0.04126297, 0.95873703],
       [0.89247508, 0.10752492],
       [0.86980974, 0.13019026]])

In [174]:
model.predict(X_test)

array([0, 0, 1, ..., 0, 0, 1])

In [175]:
model.score(X_train, y_train)

0.8214578214578214

In [176]:
model.score(X_test, y_test)

0.8237203860778005

In [180]:
from sklearn.svm import SVC

In [183]:
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [184]:
clf.predict(X_test)

array([0, 0, 1, ..., 0, 0, 1])

In [185]:
clf.score(X_train, y_train)

0.8305350805350805

In [186]:
clf.score(X_test, y_test)

0.8303305059959052